const groovytracks = [
    { file: "audio/A_Ride_in_Roadway_Street.mp3", name: "A Ride in Roadway Street", duration: "2:28" },
    { file: "audio/Airlectricity.mp3", name: "Airlectricity", duration: "1:01" },
    { file: "audio/Cybermesh.mp3", name: "Cybermesh.mp3", duration: "1:00" },
    { file: "audio/Disco_Garden.mp3", name: "Disco Garden", duration: "1:07" },
    { file: "audio/Duper_Interiors.mp3", name: "Duper Interiors", duration: "1:14" },
    { file: "audio/Duperhouse.mp3", name: "Duperhouse", duration: "1:16" },
    { file: "audio/Fansynth_Pants_Adventure.mp3", name: "Fansynth Pants Adventure", duration: "1:36" },    
    { file: "audio/Grooves_is_on_the_Case.mp3", name: "Grooves is on the Case", duration: "1:08" },
    { file: "audio/HardCORE.mp3", name: "HardCORE", duration: "1:08" },
    { file: "audio/Harpbass.mp3", name: "Harpbass", duration: "2:23" },
    { file: "audio/hollow_knight_inspired_melody_whatchamacalit.mp3", name: "hollow-knight-inspired melody whatchamacalit", duration: "1:31" },
    { file: "audio/If_Cyman_directed_an_action_blockbuster.mp3", name: "If Cyman directed an action blockbuster", duration: "2:26" },
    { file: "audio/Its_Sprint_Time.mp3", name: "It's Sprint Time!", duration: "1:34", image: "images/thumb_Its_Sprint_Time.png" },    
    { file: "audio/Maniac_Machinations.mp3", name: "Maniac Machinations", duration: "2:50", image: "images/thumb_Maniac_Machinations.png" },    
    { file: "audio/Maniac_Miscalculations.mp3", name: "Maniac Miscalculations", duration: "1:02" }, 
    { file: "audio/Metal_Cowboys.mp3", name: "Metal Cowboys", duration: "1:03" },
    { file: "audio/Party_on_Andromeda.mp3", name: "Party on Andromeda", duration: "1:08" },
    { file: "audio/Rap_Cats_Downtown.mp3", name: "Rap Cats Downtown", duration: "1:10" },
    { file: "audio/Recalibrate_Cymans_Theme.mp3", name: "Recalibrate - Cyman's Theme", duration: "1:53" },
    { file: "audio/Rowmans_Shanty.mp3", name: "Rowman's Shanty", duration: "1:02" }, 
    { file: "audio/Ta_Ren_Theme_2_0.mp3", name: "Tá Ren Theme 2.0", duration: "0:50" },
    { file: "audio/This_Is_Not_Your_Battlefield.mp3", name: "This Is Not Your Battlefield", duration: "3:00", image: "images/thumb_This_Is_Not_Your_Battlefield.png" },    
    { file: "audio/Town_Lost_in_Myth.mp3", name: "Town Lost in Myth", duration: "1:47" },
    { file: "audio/Zenith.mp3", name: "Zenith", duration: "2:50" },                                                                    
];