const groovytracks_array = [
    { file: "A_Ride_in_Roadway_Street.mp3", name: "A Ride in Roadway Street", duration: "2:28" },
    { file: "Airlectricity.mp3", name: "Airlectricity", duration: "1:01" },
    { file: "Cybermesh.mp3", name: "Cybermesh", duration: "1:00" },
    { file: "Disco_Garden.mp3", name: "Disco Garden", duration: "1:07" },
    { file: "Duper_Interiors.mp3", name: "Duper Interiors", duration: "1:14" },
    { file: "Duperhouse.mp3", name: "Duperhouse", duration: "1:16" },
    { file: "Fansynth_Pants_Adventure.mp3", name: "Fansynth Pants Adventure", duration: "1:36" },    
    { file: "Grooves_is_on_the_Case.mp3", name: "Grooves is on the Case", duration: "1:08" },
    { file: "HardCORE.mp3", name: "HardCORE", duration: "1:08" },
    { file: "Harpbass.mp3", name: "Harpbass", duration: "2:23" },
    { file: "hollow_knight_inspired_melody_whatchamacalit.mp3", name: "hollow-knight-inspired melody whatchamacalit", duration: "1:31" },
    { file: "If_Cyman_directed_an_action_blockbuster.mp3", name: "If Cyman directed an action blockbuster", duration: "2:26" },
    { file: "Its_Sprint_Time.mp3", name: "It's Sprint Time!", duration: "1:34", image: "images/thumbs/thumb_Its_Sprint_Time.png" },    
    { file: "Maniac_Machinations.mp3", name: "Maniac Machinations", duration: "2:50", image: "images/thumbs/thumb_Maniac_Machinations.png" },    
    { file: "Maniac_Miscalculations.mp3", name: "Maniac Miscalculations", duration: "1:02" }, 
    { file: "Metal_Cowboys.mp3", name: "Metal Cowboys", duration: "1:03" },
    { file: "Party_on_Andromeda.mp3", name: "Party on Andromeda", duration: "1:08" },
    { file: "Rap_Cats_Downtown.mp3", name: "Rap Cats Downtown", duration: "1:10" },
    { file: "Recalibrate_Cymans_Theme.mp3", name: "Recalibrate - Cyman's Theme", duration: "1:53" },
    { file: "Rowmans_Shanty.mp3", name: "Rowman's Shanty", duration: "1:02" }, 
    { file: "Ta_Ren_Theme_2_0.mp3", name: "Tá Ren Theme 2.0", duration: "0:50" },
    { file: "This_Is_Not_Your_Battlefield.mp3", name: "This Is Not Your Battlefield", duration: "3:00", image: "images/thumbs/thumb_This_Is_Not_Your_Battlefield.png" },    
    { file: "Town_Lost_in_Myth.mp3", name: "Town Lost in Myth", duration: "1:47" },
    { file: "Zenith.mp3", name: "Zenith", duration: "2:50" },                                                                    
];